### ISSUE TITLE
Unsupported GDP RSP commands?

### ISSUE THREAD

**Issue by nickn3710** [bluespec/RISCV_gdbstub#5]
Hello,
I'm running this and connecting it to my own RISC-V CPU.  When I run it with GDB I see it complain that some commands aren't supported:  qTStatus, Hg0, vMustReplyEmpty, qfThreadInfo, qL1200000000000000000, Hc-1, qC, qOffsets and qSymbo.  Are any of these necessary for GDB to function properly?

**Comment by rsnikhil** [comment]
I don't think any of those are necessary for GDB to function properly (by properly, I mean to support basic GDB commands such as reading/writing regs, PC, and mem, setting/removing breakpoints, continue, step, stepi, ^C, etc.)

See last two paras at https://sourceware.org/gdb/onlinedocs/gdb/Overview.html ,  "At a minimum, a stub is required to support...".

GDB will attempt a wider repertoire commands; if gdbstub does not support a command, it responds with an empty response to indicate that, and GDB learns not to use that command.

We've been using gdbstub successfully with the supported commands for some years now.

**Comment by nickn3710** [comment]
Thanks for the tips!
